### ISSUE TITLE
REPL Completion

### ISSUE THREAD

**Issue by Gavinok** [nobody-famous/alive#109]
Not sure how feasible but I think if the repl is moved to a split tab in the same way Calva does then adding completion should be possible. I figure this may be a little too late for such a drastic change but I think it would be well worth the effort in my opinion. 
![2022-09-17_10-07-15](https://user-images.githubusercontent.com/34443260/190868480-21f070d6-1554-4741-ab48-e9e5559bc5e7.png)
Added a picture for reference

**Comment by nobody-famous** [comment]
It was originally done that way. The problem is that it needs to be a text document, the same as a source code document, so completion works but everything else is a pain. It also has horrible performance that gets worse as the document grows. Doing an ASDF load on the LSP source, for example, takes maybe 1/4 of a second on the command line but would take a couple minutes with that REPL. It takes around 10 seconds with the current REPL, which is at least tolerable.

I'm not completely opposed to doing it that way, aside from it feeling more like Emacs than VSCode (my main gripe with Calva, and a big reason I don't use Clojure, is that it feels like it tries to turn VSCode into Emacs). The performance issues would need to be figured out along with the behavior of everything other than completions.

The way I currently get around the completion issue is by creating a scratch.lisp file under the .vscode directory and using that to send things to the repl. That's basically what Calva does with its repl, but doesn't require implementing command line style navigation.

**Comment by Gavinok** [comment]
Ah that makes sense. Have you considered adding the scratch pad as built in to alive? Then the users can keep a scratch pad around per project. I have been trying to introduce this to new comers and I think having a quick way to generate/access a scratchpad in the cl-user namespace would be a decent option.

**Comment by nobody-famous** [comment]
I've thought about it in passing, but not enough to iron out the details. I think it's a good idea and wouldn't be too difficult to do, just need a command that opens the file if it's there or creates it if it's not.

**Comment by nobody-famous** [comment]
The scratch pad idea has been added. There's an Open Scratch Pad command that'll open it.
