### ISSUE TITLE
Is there any way to keep my focus in the editor window when debug is triggered?

### ISSUE THREAD

**Issue by smashedtoatoms** [nobody-famous/alive#45]
I've had this weird behavior where the focus drops down into the debugger when it opens, but it only lets me scroll around.  I can't use the key commands to pick an option.  I can't figure out a way to get out of it that doesn't involve clicking my mouse back on the editor window.  Is there a way to pop the debugger open without moving the focus to it?  Is there a better way to do this that I am not aware of?  This could 100% be user error.

**Comment by nobody-famous** [comment]
I've noticed VSCode does that from time to time. When it opens a new window, the focus ends up not being on any open window and you have to click on one. I thought I had fixed that, but apparently not. I'll look into it. I think keeping the focus on the editor is the right behavior since the most common use cases don't require the debugger to be in focus.

**Comment by smashedtoatoms** [comment]
Not going to lie, I was hoping I was doing it wrong. Sorry to give you more to do. I've been using code as my daily driver for lisp though, and it's working great!  Thanks so much for your hard work.

**Comment by nobody-famous** [comment]
Turned out to be a simple fix. I had fixed it for the repl window opening, but not the debugger. :-/

Glad it's working for you! Let me know if you run into any other issues with it.

**Comment by smashedtoatoms** [comment]
Oh man, this is f**king awesome.  I haven't had to use emacs in weeks.  You're doing god's work.  Now I just have to get my code so it isn't dropping into the debugger every time I run it!
