### ISSUE TITLE
When I press the letter P with the repl attached I get an error

### ISSUE THREAD

**Issue by MarkusReynolds1989** [nobody-famous/alive#77]
![image](https://user-images.githubusercontent.com/41028417/158417732-c5fe3e9a-d069-443c-bbbb-0127b4d64dba.png)
Pressing the letter P in the repl or the text document causes the error in the screenshot, might be something wrong in my VSCode config but I checked all of the keybindings and have nothing set for P.

**Comment by nobody-famous** [comment]
Are you using Windows? I've only seen that on Windows, so I've been chalking it up to a bug in SBCL for Windows.

It happens when asking for a list of completions. I wondered if it might also happen with Emacs, so looked at the Slime source. They always send at least three characters when querying for completion, so it doesn't happen. It seems to only happen when sending a single "p" as the query. I haven't figured out why p is such a problem. Other letters return a longer list, so it's not that.

**Comment by MarkusReynolds1989** [comment]
Yeah that's correct. Thanks for responding.
